### PR TITLE
Update game code; add Seek feature

### PR DESCRIPTION
**Pull request by bash-tp**
* Updated to the latest game code, including overtime support
* Made playback more like the original (sound, scoreboard, etc.)
* Added the Seek feature to navigate within game

### CODE REVIEW

**Comment by bash-tp** [comment]
Thanks for this awesome project @keratagpro! I wanted to test my overtime script so I updated to the current global-game.js, and also made the Seek feature work so I could skip ahead to the end of the match. Most of the changes are just bringing in more files to make the game frame complete so that all scripts can be tested effectively. Feel free to incorporate these changes if you'd like.

**Comment by bash-tp** [comment]
FYI, I just push some more changes, including eggball support and a few bug fixes. I also updated all of the github references from keratagpro to bash-tp, since I've been unsuccessful at contacting Kera despite various attempts. Further development will continue at https://github.com/bash-tp/tagpro-vcr and I'll maintain the player at https://bash-tp.github.io/tagpro-vcr. Hopefully we'll be able to merge at some point.

**Comment by ronisaacson** [comment]
Closes #10.
Closes #7.
Closes #6.
Closes #4.
Closes #2.

**Comment by bash-tp** [comment]
Hi @keratagpro, fyi: now that I'm on the development team, I'm working on integrating VCR-like functionality into the game, including server-side captures. I'll continue with sporadic releases (probably only for event maps or breaking changes) until that's done. I don't plan to submit any more PRs to your repo at this point though.

**Comment by keratagpro** [comment]
Hey. Thanks for letting me know! Good to hear that it's being integrated. 👍

**Pull request merged**
